/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package elektronikstok.view;

/**
 *
 * @author tuba
 */
public class UrunSatis extends javax.swing.JFrame {

    /**
     * Creates new form UrunSatis
     */
    public UrunSatis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUrunSatis = new javax.swing.JPanel();
        lblSatUrunAdi = new javax.swing.JLabel();
        lblSatUrunAlisFiyatı = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblSatmakİstediginizMiktar = new javax.swing.JLabel();
        txtSatmakİstediginizMiktar = new javax.swing.JTextField();
        lblOdemeSekli = new javax.swing.JLabel();
        txtOdemeSekli = new javax.swing.JTextField();
        lblSatisAciklama = new javax.swing.JLabel();
        txtSatisAciklama = new javax.swing.JTextField();
        btnSatisVazgec = new javax.swing.JButton();
        btnSatisSat = new javax.swing.JButton();
        lblSatUrunSatisFiyati = new javax.swing.JLabel();
        txtSatUrunAlisFiyati = new javax.swing.JTextField();
        txtSatUrunAdi = new javax.swing.JTextField();
        txtSatUrunSatisFiyati = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlUrunSatis.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ürün Satış", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        lblSatUrunAdi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSatUrunAdi.setText("ÜRÜN ADI                              :");

        lblSatUrunAlisFiyatı.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSatUrunAlisFiyatı.setText("ALIŞ FİYATI                            :");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));

        lblSatmakİstediginizMiktar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSatmakİstediginizMiktar.setText("SATMAK İSTEDİĞİNİZ MİKTAR:");

        txtSatmakİstediginizMiktar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSatmakİstediginizMiktarActionPerformed(evt);
            }
        });

        lblOdemeSekli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblOdemeSekli.setText("ÖDEME ŞEKLİ                        :");

        txtOdemeSekli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOdemeSekliActionPerformed(evt);
            }
        });

        lblSatisAciklama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSatisAciklama.setText("AÇIKLAMA                             :");

        txtSatisAciklama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSatisAciklamaActionPerformed(evt);
            }
        });

        btnSatisVazgec.setText("Vazgeç");
        btnSatisVazgec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSatisVazgecActionPerformed(evt);
            }
        });

        btnSatisSat.setText("Sat");
        btnSatisSat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSatisSatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblSatisAciklama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblOdemeSekli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSatmakİstediginizMiktar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSatmakİstediginizMiktar)
                    .addComponent(txtOdemeSekli)
                    .addComponent(txtSatisAciklama, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSatisSat, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSatisVazgec)
                .addGap(35, 35, 35))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnSatisSat, btnSatisVazgec});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSatmakİstediginizMiktar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSatmakİstediginizMiktar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOdemeSekli, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOdemeSekli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSatisAciklama, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSatisAciklama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSatisSat, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSatisVazgec, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnSatisSat, btnSatisVazgec});

        lblSatUrunSatisFiyati.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSatUrunSatisFiyati.setText("SATIŞ FİYATI                          :");

        txtSatUrunAlisFiyati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSatUrunAlisFiyatiActionPerformed(evt);
            }
        });

        txtSatUrunAdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSatUrunAdiActionPerformed(evt);
            }
        });

        txtSatUrunSatisFiyati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSatUrunSatisFiyatiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlUrunSatisLayout = new javax.swing.GroupLayout(pnlUrunSatis);
        pnlUrunSatis.setLayout(pnlUrunSatisLayout);
        pnlUrunSatisLayout.setHorizontalGroup(
            pnlUrunSatisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUrunSatisLayout.createSequentialGroup()
                .addGroup(pnlUrunSatisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlUrunSatisLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlUrunSatisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlUrunSatisLayout.createSequentialGroup()
                                .addComponent(lblSatUrunAdi)
                                .addGap(18, 18, 18)
                                .addComponent(txtSatUrunAdi))
                            .addGroup(pnlUrunSatisLayout.createSequentialGroup()
                                .addComponent(lblSatUrunAlisFiyatı)
                                .addGap(18, 18, 18)
                                .addComponent(txtSatUrunAlisFiyati))
                            .addGroup(pnlUrunSatisLayout.createSequentialGroup()
                                .addComponent(lblSatUrunSatisFiyati)
                                .addGap(18, 18, 18)
                                .addComponent(txtSatUrunSatisFiyati, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)))
                        .addGap(31, 31, 31)))
                .addContainerGap())
        );
        pnlUrunSatisLayout.setVerticalGroup(
            pnlUrunSatisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUrunSatisLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlUrunSatisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlUrunSatisLayout.createSequentialGroup()
                        .addGroup(pnlUrunSatisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSatUrunAdi)
                            .addComponent(txtSatUrunAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblSatUrunAlisFiyatı))
                    .addComponent(txtSatUrunAlisFiyati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlUrunSatisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSatUrunSatisFiyati)
                    .addComponent(txtSatUrunSatisFiyati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlUrunSatis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlUrunSatis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSatmakİstediginizMiktarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSatmakİstediginizMiktarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSatmakİstediginizMiktarActionPerformed

    private void txtOdemeSekliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOdemeSekliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOdemeSekliActionPerformed

    private void txtSatisAciklamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSatisAciklamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSatisAciklamaActionPerformed

    private void btnSatisVazgecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSatisVazgecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSatisVazgecActionPerformed

    private void btnSatisSatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSatisSatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSatisSatActionPerformed

    private void txtSatUrunAlisFiyatiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSatUrunAlisFiyatiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSatUrunAlisFiyatiActionPerformed

    private void txtSatUrunAdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSatUrunAdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSatUrunAdiActionPerformed

    private void txtSatUrunSatisFiyatiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSatUrunSatisFiyatiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSatUrunSatisFiyatiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UrunSatis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UrunSatis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UrunSatis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UrunSatis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UrunSatis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnSatisSat;
    public javax.swing.JButton btnSatisVazgec;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lblOdemeSekli;
    public javax.swing.JLabel lblSatUrunAdi;
    public javax.swing.JLabel lblSatUrunAlisFiyatı;
    public javax.swing.JLabel lblSatUrunSatisFiyati;
    public javax.swing.JLabel lblSatisAciklama;
    public javax.swing.JLabel lblSatmakİstediginizMiktar;
    public javax.swing.JPanel pnlUrunSatis;
    public javax.swing.JTextField txtOdemeSekli;
    public javax.swing.JTextField txtSatUrunAdi;
    public javax.swing.JTextField txtSatUrunAlisFiyati;
    public javax.swing.JTextField txtSatUrunSatisFiyati;
    public javax.swing.JTextField txtSatisAciklama;
    public javax.swing.JTextField txtSatmakİstediginizMiktar;
    // End of variables declaration//GEN-END:variables
}
